version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 443:443
    restart: always
    env_file:
      - ./back/.env
    links:
      - mongo
      - redis
    volumes:                
      - uploads_data:/uploads
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - 6380:6379
volumes:
  mongo_data:
  redis_data:
  uploads_data: 