name: Build

on: [push, pull_request]

jobs:
  build-back:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci
        working-directory: ./back

      - name: Build
        run: npm run build
        working-directory: ./back

  test-back:
    needs: build-back
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci
        working-directory: ./back

      - name: Run tests
        run: npm run test
        working-directory: ./back
