name: Deploy

on: workflow_dispatch

jobs:
  deploy-production:
    runs-on: self-hosted

    if: github.ref_name == 'main'

    steps:
      - name: Move .env file to a safe place
        run: mv .env ../

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          clean: "false"

      - name: Move .env file back
        run: mv ../.env .

      - name: Git pull
        run: git pull origin main

      - name: Run Docker Compose
        run: docker-compose up --build -d
