name: Deploy

on: workflow_dispatch

jobs:
  deploy-production:
    runs-on: self-hosted

    if: github.ref_name == 'main'

    steps:
      - name: Run Docker Compose down
        run: docker-compose down

      - name: Clear Docker Cache
        run: docker system prune -a

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ./back/.env file
        run: |
          echo HOST=${{ secrets.HOST }} >> ./back/.env
          echo PORT=${{ secrets.PORT }} >> ./back/.env
          echo DB_CONN_STRING=${{ secrets.DB_CONN_STRING }} >> ./back/.env
          echo JWTSECRET=${{ secrets.JWTSECRET }} >> ./back/.env
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> ./back/.env
          echo SSL_KEY_PATH=${{ secrets.SSL_KEY_PATH }} >> ./back/.env
          echo SSL_CERT_PATH=${{ secrets.SSL_CERT_PATH }} >> ./back/.env
          echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> ./back/.env
          echo REDIS_PORT=${{ secrets.REDIS_PORT }} >> ./back/.env
          echo REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} >> ./back/.env

      - name: Create .env file
        run: |
            echo MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }} >> ./.env
            echo MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }} >> ./.env
            echo REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} >> ./.env

      - name: Create .key file
        run: |
          echo "${{ secrets.CERT_KEY }}" > ./back/localhost.key
        shell: bash

      - name: Create .crt file
        run: |
          echo "${{ secrets.CERT_CRT }}" > ./back/localhost.crt
        shell: bash
  
      - name: Run Docker Compose up
        run: docker-compose up --build -d
